# Generated by Django 2.2.2 on 2019-06-20 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='主题')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['text'],
                'verbose_name_plural': '主题',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='具体知识')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Topic', verbose_name='主题')),
            ],
            options={
                'ordering': ['text'],
                'verbose_name_plural': '具体知识',
            },
        ),
    ]
