# Generated by Django 2.1.3 on 2018-11-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='具体知识')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Topic', verbose_name='主题')),
            ],
            options={
                'verbose_name_plural': '具体知识',
                'ordering': ['text'],
            },
        ),
    ]
